name: Sync Github Repos To Gitee

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: sync-gitee-mirror
      uses: abersheeran/sync-gitee-mirror@v1-beta
      with:
        repository: abersheeran/sync-gitee-mirror
        username: ${{ secrets.GITEE_USERNAME }}
        password: ${{ secrets.GITEE_PASSWORD }}
